### ISSUE TITLE
lua runtime error

### ISSUE THREAD

**Issue by alkai** [DiscipleOfEris/Windower4Addons#1]
fastfollow: lua runtime error: fastfollow/fastfollow.lua:410: attempt to index local 'A' (a nil value)

Getting this after doing //ffo me
Everything works fine though, tried duobox only.

**Comment by alkai** [comment]
After some more testing I'm also getting this:
Gearswap/flow.lua:374: attempt to index field '?' (a nil value)
Same setup as above, addon still working.

**Comment by DiscipleOfEris** [comment]
What version of Windower and FFXI are you using?

**Comment by alkai** [comment]
Live version of FFXI, Windower4.
Should add that I only get these messages on my 2nd char, the one that starts following.

**Comment by DiscipleOfEris** [comment]
Alright, try the latest version, FastFollow v1.2.3. Should be fixed now.

**Comment by alkai** [comment]
Tested for a few hours, the initial error msg (fastfollow.lua:410: attempt to index local 'A' (a nil value)) appear to be gone but still getting Gearswap/flow.lua:374 errors. Again only on the char that is following

**Comment by DiscipleOfEris** [comment]
Do you know what action causes the error message to appear? Looks like GearSwap tries to create a packet from cache and it doesn't exist sometimes.

**Comment by alkai** [comment]
All I'm doing is //ffo me and the character that starts following get these messages eventually. In terms of what my follower char is doing it's usually singing bard songs and using ja like nightingale or troubadour but tbh I'm not convinced it's based on that as I can swap the characters around and I'll get the same msg on my main instead. Sometimes it comes after 5 min other times it takes longer.
A bit earlier I got the same error as post 6 but this time flow.lua:440 instead.

Wish I could be of more help, I'll try looking out for patterns. But again, the addon is working fine so it's probably not something you should waste much time on.
